version: "3"
services:
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./server
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
